### ISSUE TITLE
"Can't find a suitable configuration file in this directory or any parent."

### ISSUE THREAD

**Issue by paulrosen** [fwouts/previewjs#465]
### Describe the bug

When starting WebStorm I get the message "Preview.js crashed".

It says it is looking for a docker-compose file, but I have one. Here is my docker setup:

docker-compose.yml:
```
version: '3.7'

services:
  app:
    image: nmpvue3
    build: .
    container_name: nmpvue3
    volumes:
      - .:/srv/app
      - ../srf:/srv/srf
      - ./node_modules:/srv/app/node_modules
networks:
  default:
    external: true
    name: docker_default
```

Dockerfile:
```
FROM node:16.10.0

RUN apt-get update
RUN apt-get -y install default-jdk

RUN npm install -g npm@8.6.0

RUN npm install -g nodemon

RUN mkdir /srv/app && chown node:node /srv/app

USER node

WORKDIR /srv/app
```

### Reproduction

1. install preview.js from preferences/plugins/marketplace
2. restart webstorm by clicking the link asking to restart

### Preview.js version

v1.6.0

### System Info

```shell
macbookpro
webstorm
node is installed in a Docker instance NOT in mac OS
```

### Used Package Manager

npm

### Preview.js logs (check bottom panel in IntelliJ)

```shell
Preview.js crashed
Please report this issue at https://github.com/fwouts/previewjs/issues java.lang.Error: Can't find a suitable configuration file in this directory or any parent. Are you in the right directory? Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml at com.previewjs.intellij.plugin.services.PreviewJsSharedService.isInstalled(PreviewJsService.kt:132) at com.previewjs.intellij.plugin.services.PreviewJsSharedService.access$isInstalled(PreviewJsService.kt:33) at com.previewjs.intellij.plugin.services.PreviewJsSharedService$actor$1.invokeSuspend(PreviewJsService.kt:67) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
```


### Browser logs (useful for rendering errors)

_No response_

### Anything else?

_No response_
